### ISSUE TITLE
Fix Small screen responsive layout 

### ISSUE THREAD

**Issue by BinaryFox83** [audit-hero/issues#1]
I really appreciate the idea, just wanted to report a small issue with small screen responsiveness for "Finding" section.

Device: Samsung S21
Browser: Chrome

Screenshot:
![Screenshot_20221211-184514_Chrome](https://user-images.githubusercontent.com/14966614/206919837-5076a2de-dd8a-44fc-b1fa-3209663162c8.jpg)

**Comment by totovoto** [comment]
Should be fixed

**Comment by BinaryFox83** [comment]
Fix confirmed. Thank you
