### ISSUE TITLE
unable to save posts

### ISSUE THREAD

**Issue by balook** [audit-hero/issues#2]
The site showing sign the message with the wallet but the wallet not asking for any sign messages (I have unlocked the metamask already) but still the popup not showing .

and 

please make the site responsive for mobile too

**Comment by tonisives** [comment]
Can you try login again? Mobile should be fixed also.

**Comment by totovoto** [comment]
Can you try login again? Mobile should also be fixed

**Comment by balook** [comment]
hey toho working fine ,
Thanks for quick fix and auto search feature.
implement dark mode too :)

**Comment by totovoto** [comment]
I personally use https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en for dark mode. Maybe Ill add a button sometime also
