### ISSUE TITLE
Incorrect reward amount

### ISSUE THREAD

**Issue by c14sh** [audit-hero/issues#7]
![image](https://github.com/audit-hero/issues/assets/135066679/c3dc1398-a7d5-4006-9388-9a2ede0efa7e)

The reward amount is smaller than what's displayed on Code4rena website.
![image](https://github.com/audit-hero/issues/assets/135066679/50b693bc-fc8b-467b-857d-af816eee93e7)

Not sure if Code4rena API is wrong or your calculation has a glitch. Where is Code4rena API?

**Comment by tonisives** [comment]
fixed
